package com.enterprise.reporting.service;

import com.enterprise.reporting.model.Report;
import com.enterprise.reporting.model.User;
import com.enterprise.reporting.repository.ReportRepository;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lombok.RequiredArgsConstructor;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ReportService {

    private final ReportRepository reportRepository;
    private final DataService dataService;

    public byte[] generateWeeklyPdf(User user) throws DocumentException {
        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, out);

        document.open();
        Font font = FontFactory.getFont(FontFactory.HELVETICA_BOLD);
        font.setSize(18);

        Paragraph p = new Paragraph("Weekly Enterprise Report", font);
        p.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(p);

        document.add(new Paragraph("Generated by: " + user.getUsername()));
        document.add(new Paragraph("Date: " + LocalDateTime.now()));
        document.add(new Paragraph(" "));

        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.addCell("Department");
        table.addCell("Revenue");
        table.addCell("Growth %");
        table.addCell("Performance");

        List<DataService.DepartmentMetric> metrics = dataService.getWeeklyMetrics();
        for (DataService.DepartmentMetric m : metrics) {
            table.addCell(m.getDepartment());
            table.addCell(String.format("$%.2f", m.getRevenue()));
            table.addCell(String.format("%.2f%%", m.getGrowth()));
            table.addCell(m.getPerformance() + "%");
        }

        document.add(table);
        document.close();

        saveReportMetadata("Weekly Report", "pdf", user);

        return out.toByteArray();
    }

    public byte[] generateWeeklyExcel(User user) throws IOException {
        try (Workbook workbook = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Sheet sheet = workbook.createSheet("Weekly Report");
            Row header = sheet.createRow(0);
            header.createCell(0).setCellValue("Department");
            header.createCell(1).setCellValue("Revenue");
            header.createCell(2).setCellValue("Growth %");
            header.createCell(3).setCellValue("Performance");

            List<DataService.DepartmentMetric> metrics = dataService.getWeeklyMetrics();
            int rowIdx = 1;
            for (DataService.DepartmentMetric m : metrics) {
                Row row = sheet.createRow(rowIdx++);
                row.createCell(0).setCellValue(m.getDepartment());
                row.createCell(1).setCellValue(m.getRevenue());
                row.createCell(2).setCellValue(m.getGrowth());
                row.createCell(3).setCellValue(m.getPerformance());
            }

            workbook.write(out);
            saveReportMetadata("Weekly Report", "excel", user);
            return out.toByteArray();
        }
    }

    private void saveReportMetadata(String name, String type, User user) {
        reportRepository.save(Report.builder()
            .name(name)
            .type(type)
            .category("weekly")
            .createdAt(LocalDateTime.now())
            .createdBy(user)
            .build());
    }

    public List<Report> getReportHistory() {
        return reportRepository.findAll();
    }
}
